import json
from src.logger import logger

def parse_json_from_text(raw_text: str):
    """
    Safely extracts and parses JSON from raw string output generated by LLMs.
    Handles Markdown backticks and extraneous text.
    Returns the parsed JSON object/array, or None if completely failed.
    """
    raw_text = raw_text.strip()
    
    # Try array first
    start_idx = raw_text.find('[')
    end_idx = raw_text.rfind(']')
    if start_idx != -1 and end_idx != -1 and end_idx > start_idx:
        json_str = raw_text[start_idx:end_idx+1]
        try:
            parsed = json.loads(json_str)
            return parsed
        except Exception as e:
            logger.debug(f"[json_parser] Failed to parse array: {e}")
            pass

    # Try object next
    start_idx_dict = raw_text.find('{')
    end_idx_dict = raw_text.rfind('}')
    if start_idx_dict != -1 and end_idx_dict != -1 and end_idx_dict > start_idx_dict:
        json_str = raw_text[start_idx_dict:end_idx_dict+1]
        try:
            parsed = json.loads(json_str)
            if isinstance(parsed, dict):
                if "steps" in parsed and isinstance(parsed["steps"], list):
                    return parsed["steps"]
                return [parsed]
            return parsed
        except Exception as e:
            logger.debug(f"[json_parser] Failed to parse dict: {e}")
            pass

    # Try pure raw text fallback
    try:
        return json.loads(raw_text)
    except Exception as e:
        logger.debug(f"[json_parser] Final fallback parse failed: {e}")
        return None
